### PR TITLE
address Issue 7

### PR DESCRIPTION
**Pull request by yuri-scarbaci-lenio**
[as per discussed in this issue](https://github.com/webdeb/next-styles/issues/7)
applied changes to allow the configuration of miniCssExtractOptions and updated documentation as fit

### CODE REVIEW

**Comment by webdeb** [comment]
Looks good to me thank you!
please update the version to `1.0.7` because 1.0.6 is already published, just forgot to push it into the repo

**Comment by yuri-scarbaci-lenio** [comment]
Done

**Comment by webdeb** [comment]
Thanks, published!

**Comment by webdeb** [comment]
fixes #7

**Pull request merged**
